//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualStudioFileTimeline {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualStudioFileTimeline.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Difference - {0} 的本地化字符串。
        /// </summary>
        public static string Caption_ComparisonTitleFormat {
            get {
                return ResourceManager.GetString("Caption_ComparisonTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeline 的本地化字符串。
        /// </summary>
        public static string Caption_ToolWindow {
            get {
                return ResourceManager.GetString("Caption_ToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileTimeline 的本地化字符串。
        /// </summary>
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string MenuItem_Header_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Header_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open With Explorer 的本地化字符串。
        /// </summary>
        public static string MenuItem_Header_OpenWithExplorer {
            get {
                return ResourceManager.GetString("MenuItem_Header_OpenWithExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Content 的本地化字符串。
        /// </summary>
        public static string MenuItem_Header_RestoreContent {
            get {
                return ResourceManager.GetString("MenuItem_Header_RestoreContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Content 的本地化字符串。
        /// </summary>
        public static string MenuItem_Header_ViewContent {
            get {
                return ResourceManager.GetString("MenuItem_Header_ViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalHistory 的本地化字符串。
        /// </summary>
        public static string ProviderDescription_LocalHistory {
            get {
                return ResourceManager.GetString("ProviderDescription_LocalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} days 的本地化字符串。
        /// </summary>
        public static string TimeDisplayFormat_Day {
            get {
                return ResourceManager.GetString("TimeDisplayFormat_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} hours 的本地化字符串。
        /// </summary>
        public static string TimeDisplayFormat_Hour {
            get {
                return ResourceManager.GetString("TimeDisplayFormat_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} minutes 的本地化字符串。
        /// </summary>
        public static string TimeDisplayFormat_Minute {
            get {
                return ResourceManager.GetString("TimeDisplayFormat_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} months 的本地化字符串。
        /// </summary>
        public static string TimeDisplayFormat_Month {
            get {
                return ResourceManager.GetString("TimeDisplayFormat_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 now 的本地化字符串。
        /// </summary>
        public static string TimeDisplayFormat_Now {
            get {
                return ResourceManager.GetString("TimeDisplayFormat_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} weeks 的本地化字符串。
        /// </summary>
        public static string TimeDisplayFormat_Week {
            get {
                return ResourceManager.GetString("TimeDisplayFormat_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} years 的本地化字符串。
        /// </summary>
        public static string TimeDisplayFormat_Year {
            get {
                return ResourceManager.GetString("TimeDisplayFormat_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 saved file 的本地化字符串。
        /// </summary>
        public static string TimelineItemSource_SavedFile {
            get {
                return ResourceManager.GetString("TimelineItemSource_SavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 search replace 的本地化字符串。
        /// </summary>
        public static string TimelineItemSource_SearchReplace {
            get {
                return ResourceManager.GetString("TimelineItemSource_SearchReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current file does not have any historical records yet. 的本地化字符串。
        /// </summary>
        public static string View_Tips_NoHistoryNow {
            get {
                return ResourceManager.GetString("View_Tips_NoHistoryNow", resourceCulture);
            }
        }
    }
}
